In [1]:
import numpy as np
from scipy.optimize import linprog
from ipynb.fs.full.functions import nn2na, get_selected_arcs

In [2]:
#Import data
NN = np.array([[0, 1, 1, 0, 0, 0],
               [0, 0, 0, 1, 0, 1],
               [0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 0]])
beq = np.array([1, 0, 0, 0, 0, -1])
C = np.array([2, 2, 2, 5, 2, 1, 2])

In [3]:
# Call nn2na function in order to obtain Node-Arc matrix. We'll use it later on in linprog:
Aeq, arc_idxs, arc_idxs_list = nn2na(NN)
# Create a tuple with every arc lower and upper bounds. In this case we have no upper limit:
bounds = tuple([(0, None) for arcs in range(0, Aeq.shape[1])])

In [4]:
print('## Optimizer inputs ## \n'
      'Cost vector: %s \n'
      'A_eq Node-Arc matrix:\n%s \n'
      'b_eq demand-supply vector: %s \n'
      'Bounds of each X arc variable: %s \n' % (C, Aeq, beq, bounds)) 

## Optimizer inputs ## 
Cost vector: [2 2 2 5 2 1 2] 
A_eq Node-Arc matrix:
[[ 1  1  0  0  0  0  0]
 [-1  0  1  1  0  0  0]
 [ 0 -1  0  0  1  0  0]
 [ 0  0 -1  0  0  1  0]
 [ 0  0  0  0 -1  0  1]
 [ 0  0  0 -1  0 -1 -1]] 
b_eq demand-supply vector: [ 1  0  0  0  0 -1] 
Bounds of each X arc variable: ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None)) 



In [5]:
# Call linprog function to optimize. It'll return te Shortest Path and the value of the Objetive Function:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds)

C:\Users\joaquin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  


In [6]:
# GET THE SOLUTION:
selarcs = get_selected_arcs(arc_idxs, res.x)
print('## Results ##')
print('The raw solution will be: %s' % res.x)
print('The arcs that make the shortest path will be (from, to): %s' % selarcs)
print('The minimum cost will be: %0.2f ' % res.fun)

## Results ##
The raw solution will be: [1.00000000e+00 1.07463814e-10 1.00000000e+00 4.87243454e-11
 1.07463814e-10 1.00000000e+00 1.07463814e-10]
The arcs that make the shortest path will be (from, to): [(0, 1), (1, 3), (3, 5)]
The minimum cost will be: 5.00 
