In [1]:
import numpy as np
from scipy.optimize import linprog
from ipynb.fs.full.functions import nn2na, get_selected_arcs

In [2]:
#Import data
NN = np.array([[0, 1, 1, 0, 0, 0],
               [0, 0, 0, 1, 0, 1],
               [0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 0]])
beq = np.array([1, 0, 0, 0, 0, -1])
C = np.array([2, 1, 2, 5, 2, 1, 2])

In [3]:
# DATA transforming for optimization:
Aeq, arc_idxs = nn2na(NN)
bounds = tuple([(0, None) for arcs in range(0, Aeq.shape[1])])

In [4]:
print('## Optimizer inputs ## \n'
      'Cost vector: %s \n'
      'A_eq Node-Arc matrix:\n%s \n'
      'b_eq demand-supply vector: %s \n'
      'Bounds of each X arc variable: %s \n' % (C, Aeq, beq, bounds)) 

## Optimizer inputs ## 
Cost vector: [2 1 2 5 2 1 2] 
A_eq Node-Arc matrix:
[[ 1  1  0  0  0  0  0]
 [-1  0  1  1  0  0  0]
 [ 0 -1  0  0  1  0  0]
 [ 0  0 -1  0  0  1  0]
 [ 0  0  0  0 -1  0  1]
 [ 0  0  0 -1  0 -1 -1]] 
b_eq demand-supply vector: [ 1  0  0  0  0 -1] 
Bounds of each X arc variable: ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None)) 



In [5]:
# OPTIMIZE:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds, method='simplex')

C:\Users\joaquin\Anaconda3\lib\site-packages\scipy\optimize\_linprog_util.py:704: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  warn(redundancy_warning, OptimizeWarning)


In [6]:
# GET THE SOLUTION:
selarcs = get_selected_arcs(arc_idxs, res.x)
print('## Results Using Simplex##')
print('The raw solution will be: %s' % res.x)
print('The arcs that make the shortest path will be (from, to): %s' % selarcs)
print('The minimum cost will be: %0.2f ' % res.fun)

## Results Using Simplex##
The raw solution will be: [0. 1. 0. 0. 1. 0. 1.]
The arcs that make the shortest path will be (from, to): [(0, 2), (2, 4), (4, 5)]
The minimum cost will be: 5.00 


In [7]:
# OPTIMIZE:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds, method='interior-point')

In [8]:
# GET THE SOLUTION:
selarcs = get_selected_arcs(arc_idxs, res.x)
print('## Results using Interior Points##')
print('The raw solution will be: %s' % res.x)
print('The arcs that make the shortest path will be (from, to): %s' % selarcs)
print('The minimum cost will be: %0.2f ' % res.fun)

## Results using Interior Points##
The raw solution will be: [5.29117485e-01 4.70882515e-01 5.29117485e-01 1.92890873e-11
 4.70882515e-01 5.29117485e-01 4.70882515e-01]
The arcs that make the shortest path will be (from, to): []
The minimum cost will be: 5.00 


#### CONCLUSION
We see that SIMPLEX method solves our problem perfectly well. On the contrary, INTERIOR-POINT, although it arrives at the same OF value, it fails to select a path. We get non integer values for Decision Variables. That, of course is not acceptable.