In [1]:
import numpy as np
from scipy.optimize import linprog
from ipynb.fs.full.functions import nn2na, get_selected_arcs

In [2]:
#Import data
NN = np.array([[0, 1, 1, 0, 0, 0],
               [0, 0, 0, 1, 0, 1],
               [0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 1],
               [1, 0, 0, 0, 0, 0]])
beq = np.array([0, 0, 0, 0, 0, 0])
C = np.array([0, 0, 0, 0, 0, 0, 0, -1])
upper_b = [7, 1, 2, 3, 2, 1, 2, None]

In [3]:
# DATA transforming for optimization:
Aeq, arc_idxs = nn2na(NN)
bounds = tuple([(0, upper_b[arcs]) for arcs in range(0, Aeq.shape[1])])

In [4]:
print(bounds)

((0, 7), (0, 1), (0, 2), (0, 3), (0, 2), (0, 1), (0, 2), (0, None))


In [5]:
print('## Optimizer inputs ## \n'
      'Cost vector: %s \n'
      'A_eq Node-Arc matrix:\n%s \n'
      'b_eq demand-supply vector: %s \n'
      'Bounds of each X arc variable: %s \n' % (C, Aeq, beq, bounds)) 

## Optimizer inputs ## 
Cost vector: [ 0  0  0  0  0  0  0 -1] 
A_eq Node-Arc matrix:
[[ 1  1  0  0  0  0  0 -1]
 [-1  0  1  1  0  0  0  0]
 [ 0 -1  0  0  1  0  0  0]
 [ 0  0 -1  0  0  1  0  0]
 [ 0  0  0  0 -1  0  1  0]
 [ 0  0  0 -1  0 -1 -1  1]] 
b_eq demand-supply vector: [0 0 0 0 0 0] 
Bounds of each X arc variable: ((0, 7), (0, 1), (0, 2), (0, 3), (0, 2), (0, 1), (0, 2), (0, None)) 



In [6]:
# OPTIMIZE:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds, method='simplex')

C:\Users\joaquin\Anaconda3\lib\site-packages\scipy\optimize\_linprog_util.py:704: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  warn(redundancy_warning, OptimizeWarning)


In [7]:
# GET THE SOLUTION:
selarcs = get_selected_arcs(arc_idxs, res.x)
print('## Results Using Simplex##')
print('The raw solution will be: %s' % res.x)
print('The arcs that make the shortest path will be (from, to): %s' % selarcs)
print('The minimum cost will be: %0.2f ' % res.fun)

## Results Using Simplex##
The raw solution will be: [4. 1. 1. 3. 1. 1. 1. 5.]
The arcs that make the shortest path will be (from, to): [(0, 2), (1, 3), (2, 4), (3, 5), (4, 5)]
The minimum cost will be: -5.00 


In [9]:
arc_idxs

[(0, 1), (0, 2), (1, 3), (1, 5), (2, 4), (3, 5), (4, 5), (5, 0)]