In [1]:
import numpy as np

In [2]:
#Import data
residual_G = np.array([[0, 7, 1, 0, 0, 0], #s
                       [0, 0, 0, 2, 0, 3], #2
                       [0, 0, 0, 0, 2, 0], #3
                       [0, 0, 0, 0, 0, 1], #4
                       [0, 0, 0, 0, 0, 2], #5
                       [0, 0, 0, 0, 0, 0]]) #t
succ = [[1, 2], [3, 5], [4], [5], [5], []]

# Other possibilities:
#residual_G = [[7, 1, 2, 3, 2, 1, 2], [0, 0, 0, 0, 0, 0, 0]]
#succ = {'s':[2, 3], 2:[4, 't'], 3:['5'], 4:['t'], 5:['t']}

In [3]:
def dfs(actual, end, path, succ):
    if actual != end:
        for nextt in succ[actual]:
            dfs(nextt, end, path, succ)
            if path != []:
                path.append(actual) #
                break
        
    else:
        path.append(actual)# 
        return path
    return path


In [4]:
path = []
total_flow = 0
final_paths =[]
path = dfs(0, 5, path, succ)
path

[5, 3, 1, 0]

In [5]:
while path != []:
    path_arcs = [ [path[i+1], path[i] ] for i in range(len(path)-1)]
    arcs_flow = [residual_G[i,j] for i,j in path_arcs]
    path_flow = min(arcs_flow)
    total_flow = total_flow + path_flow # Accumulate flows
    final_paths.append(path) # Appends paths
    print ('Path: %s \n'
           'Arc´s indpendent Flow: %s \n'
           'Path Flow: %s'%(path, arcs_flow, path_flow))
    
    for i,j in path_arcs:
        residual_G[i,j] = residual_G[i,j] - path_flow
        residual_G[j,i] = residual_G[j,i] + path_flow
        if residual_G[i][j] > 0:
            succ[i].append(j)
            succ[i] = list(set(succ[i]))
        else:
            succ[i].remove(j)
    print('Resulting Residuals: %s \n'
          'Actualized succesors: %s \n'%(residual_G, succ))
    
    path = []
    path = dfs(0, 5, path, succ)


Path: [5, 3, 1, 0] 
Arc´s indpendent Flow: [1, 2, 7] 
Path Flow: 1
Resulting Residuals: [[0 6 1 0 0 0]
 [1 0 0 1 0 3]
 [0 0 0 0 2 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 2]
 [0 0 0 1 0 0]] 
Actualized succesors: [[1, 2], [3, 5], [4], [], [5], []] 

Path: [5, 1, 0] 
Arc´s indpendent Flow: [3, 6] 
Path Flow: 3
Resulting Residuals: [[0 3 1 0 0 0]
 [4 0 0 1 0 0]
 [0 0 0 0 2 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 2]
 [0 3 0 1 0 0]] 
Actualized succesors: [[1, 2], [3], [4], [], [5], []] 

Path: [5, 4, 2, 0] 
Arc´s indpendent Flow: [2, 2, 1] 
Path Flow: 1
Resulting Residuals: [[0 3 0 0 0 0]
 [4 0 0 1 0 0]
 [1 0 0 0 1 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 1]
 [0 3 0 1 1 0]] 
Actualized succesors: [[1], [3], [4], [], [5], []] 



In [6]:
print('The total Flow through the network is: %s'%(total_flow))

The total Flow through the network is: 5
