In [1]:
import numpy as np
from scipy.optimize import linprog
from ipynb.fs.full.functions import nn2na, arcs_w_flow

In [2]:
#Import data
NN = np.array([[0, 0, 0, 1, 1],
               [0, 0, 0, 1, 1],
               [0, 0, 0, 1, 1],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])
beq = np.array([10, 20, 15, -25, -20])
C = np.array([10, 20, 10, 10, 10, 30])

In [3]:
# DATA transforming for optimization:
Aeq, arc_idxs = nn2na(NN)
bounds = tuple([(0, None) for arcs in range(0, Aeq.shape[1])])

In [4]:
print('## Optimizer inputs ## \n'
      'Cost vector: %s \n'
      'A_eq Node-Arc matrix:\n%s \n'
      'b_eq demand-supply vector: %s \n'
      'Bounds of each X arc variable: %s \n' % (C, Aeq, beq, bounds)) 

## Optimizer inputs ## 
Cost vector: [10 20 10 10 10 30] 
A_eq Node-Arc matrix:
[[ 1  1  0  0  0  0]
 [ 0  0  1  1  0  0]
 [ 0  0  0  0  1  1]
 [-1  0 -1  0 -1  0]
 [ 0 -1  0 -1  0 -1]] 
b_eq demand-supply vector: [ 10  20  15 -25 -20] 
Bounds of each X arc variable: ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None)) 



In [5]:
# OPTIMIZE:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds, method='simplex')

C:\Users\joaquin\Anaconda3\lib\site-packages\scipy\optimize\_linprog_util.py:704: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  warn(redundancy_warning, OptimizeWarning)


In [6]:
print(res.x, res.fun)

[10.  0.  0. 20. 15.  0.] 450.0


In [7]:
# PRESENTING THE SOLUTION:
arcs_flow = arcs_w_flow(arc_idxs, res.x)
print('## Transport results ## \n'
      'The minimum cost to transport every unit is: %s \n'
      'The units to be transported through each arc are (from, to): %s \n'%(res.fun, arcs_flow))

## Transport results ## 
The minimum cost to transport every unit is: 450.0 
The units to be transported through each arc are (from, to): {(0, 3): 10.0, (1, 4): 20.0, (2, 3): 15.0} 

